### ISSUE TITLE
Add Support for Bundle transaction if not multiple atleast 2 

### ISSUE THREAD

**Issue by Meetmetha** [simonmullaney/FriendlyFlashbotsPopup#1]
So It would be great if you can add bundle transaction like one bundle to send eth from Wallet A to B and Second Bundle which can use receieved funds to pay for gas for any coin transfer or any particular use case

**Comment by simonmullaney** [comment]
First issue :-) Thanks @Meetmetha. 

This enhancement is addressed in the latest commit afff13c578754483b72bb875c2ee28ea449fada6 

Functionality can be seen in: https://www.youtube.com/watch?v=qOaR8U09ESQ

Let me know if any more issues or anything else you think would be good to add to the project by opening another issue!
